language: ruby
bundler_args: --without development
script:
  - 'bundle exec rubocop .'
  - 'bundle exec foodcritic -f ~FC033 .'
  - 'bundle exec rspec spec'
  - 'bundle exec kitchen test'
rvm:
  - 2.2.2
gemfile:
  - Gemfile
branches:
  only:
    - master
